// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: schemas/logs/v1/log.proto

package logsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	LogLevel_LOG_LEVEL_UNSPECIFIED LogLevel = 0
	LogLevel_DEBUG                 LogLevel = 1
	LogLevel_INFO                  LogLevel = 2
	LogLevel_WARN                  LogLevel = 3
	LogLevel_ERROR                 LogLevel = 4
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "LOG_LEVEL_UNSPECIFIED",
		1: "DEBUG",
		2: "INFO",
		3: "WARN",
		4: "ERROR",
	}
	LogLevel_value = map[string]int32{
		"LOG_LEVEL_UNSPECIFIED": 0,
		"DEBUG":                 1,
		"INFO":                  2,
		"WARN":                  3,
		"ERROR":                 4,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_schemas_logs_v1_log_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_schemas_logs_v1_log_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_schemas_logs_v1_log_proto_rawDescGZIP(), []int{0}
}

type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ts            int64                  `protobuf:"varint,1,opt,name=ts,proto3" json:"ts,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Level         LogLevel               `protobuf:"varint,3,opt,name=level,proto3,enum=LogLevel" json:"level,omitempty"`
	Msg           string                 `protobuf:"bytes,4,opt,name=msg,proto3" json:"msg,omitempty"`                        // max length: 65500
	TraceId       string                 `protobuf:"bytes,5,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // max 64
	SpanId        string                 `protobuf:"bytes,6,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`    // max 64
	Host          string                 `protobuf:"bytes,7,opt,name=host,proto3" json:"host,omitempty"`                      // max 64
	Env           string                 `protobuf:"bytes,8,opt,name=env,proto3" json:"env,omitempty"`                        // max 32
	Version       string                 `protobuf:"bytes,9,opt,name=version,proto3" json:"version,omitempty"`                // max 32
	Tags          []string               `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Meta          map[string]string      `protobuf:"bytes,11,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	SchemaVersion string                 `protobuf:"bytes,12,opt,name=schema_version,json=schemaVersion,proto3" json:"schema_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_schemas_logs_v1_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_schemas_logs_v1_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_schemas_logs_v1_log_proto_rawDescGZIP(), []int{0}
}

func (x *LogEvent) GetTs() int64 {
	if x != nil {
		return x.Ts
	}
	return 0
}

func (x *LogEvent) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogEvent) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

func (x *LogEvent) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *LogEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogEvent) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogEvent) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *LogEvent) GetEnv() string {
	if x != nil {
		return x.Env
	}
	return ""
}

func (x *LogEvent) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LogEvent) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *LogEvent) GetMeta() map[string]string {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *LogEvent) GetSchemaVersion() string {
	if x != nil {
		return x.SchemaVersion
	}
	return ""
}

var File_schemas_logs_v1_log_proto protoreflect.FileDescriptor

const file_schemas_logs_v1_log_proto_rawDesc = "" +
	"\n" +
	"\x19schemas/logs/v1/log.proto\"\x8a\x03\n" +
	"\bLogEvent\x12\x0e\n" +
	"\x02ts\x18\x01 \x01(\x03R\x02ts\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1f\n" +
	"\x05level\x18\x03 \x01(\x0e2\t.LogLevelR\x05level\x12\x10\n" +
	"\x03msg\x18\x04 \x01(\tR\x03msg\x12\x19\n" +
	"\btrace_id\x18\x05 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x06 \x01(\tR\x06spanId\x12\x12\n" +
	"\x04host\x18\a \x01(\tR\x04host\x12\x10\n" +
	"\x03env\x18\b \x01(\tR\x03env\x12\x18\n" +
	"\aversion\x18\t \x01(\tR\aversion\x12\x12\n" +
	"\x04tags\x18\n" +
	" \x03(\tR\x04tags\x12'\n" +
	"\x04meta\x18\v \x03(\v2\x13.LogEvent.MetaEntryR\x04meta\x12%\n" +
	"\x0eschema_version\x18\f \x01(\tR\rschemaVersion\x1a7\n" +
	"\tMetaEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01J\x04\b\r\x10\x0eJ\x04\b\x0e\x10\x0fJ\x04\b\x0f\x10\x10*O\n" +
	"\bLogLevel\x12\x19\n" +
	"\x15LOG_LEVEL_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05DEBUG\x10\x01\x12\b\n" +
	"\x04INFO\x10\x02\x12\b\n" +
	"\x04WARN\x10\x03\x12\t\n" +
	"\x05ERROR\x10\x04BPZNgithub.com/UdayMalviya/logging_and_observability_system/schemas/logs/v1;logsv1b\x06proto3"

var (
	file_schemas_logs_v1_log_proto_rawDescOnce sync.Once
	file_schemas_logs_v1_log_proto_rawDescData []byte
)

func file_schemas_logs_v1_log_proto_rawDescGZIP() []byte {
	file_schemas_logs_v1_log_proto_rawDescOnce.Do(func() {
		file_schemas_logs_v1_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schemas_logs_v1_log_proto_rawDesc), len(file_schemas_logs_v1_log_proto_rawDesc)))
	})
	return file_schemas_logs_v1_log_proto_rawDescData
}

var file_schemas_logs_v1_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_schemas_logs_v1_log_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_schemas_logs_v1_log_proto_goTypes = []any{
	(LogLevel)(0),    // 0: LogLevel
	(*LogEvent)(nil), // 1: LogEvent
	nil,              // 2: LogEvent.MetaEntry
}
var file_schemas_logs_v1_log_proto_depIdxs = []int32{
	0, // 0: LogEvent.level:type_name -> LogLevel
	2, // 1: LogEvent.meta:type_name -> LogEvent.MetaEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_schemas_logs_v1_log_proto_init() }
func file_schemas_logs_v1_log_proto_init() {
	if File_schemas_logs_v1_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schemas_logs_v1_log_proto_rawDesc), len(file_schemas_logs_v1_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schemas_logs_v1_log_proto_goTypes,
		DependencyIndexes: file_schemas_logs_v1_log_proto_depIdxs,
		EnumInfos:         file_schemas_logs_v1_log_proto_enumTypes,
		MessageInfos:      file_schemas_logs_v1_log_proto_msgTypes,
	}.Build()
	File_schemas_logs_v1_log_proto = out.File
	file_schemas_logs_v1_log_proto_goTypes = nil
	file_schemas_logs_v1_log_proto_depIdxs = nil
}
